# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

#calculate fibonacci number
#stop when greater than 4 million
#sum even valued terms

def sum_even_values_fibonacci(less_than)
  fibonacci=[1,2]
  x=2
  while (fibonacci[x-1]+fibonacci[x-2])<less_than do 
    fibonacci<<(fibonacci[x-1]+fibonacci[x-2])
    x+=1
  end 
  fibonacci.select(&:even?).inject(&:+) 
end